### ISSUE TITLE
WindiCSS.default is not a function

### ISSUE THREAD

**Issue by maximimaxima** [alteredorange/directus-sveltekit-blog-starter#2]
npm run dev

> directus-svelte-starter@0.0.1 dev
> concurrently --names "directus, svelte" --prefix "{name}:" --prefix-colors "blue,red" --kill-others "pnpm run directus start"  "svelte-kit dev"

 svelte: > WindiCSS.default is not a function
 svelte:     at file:///C:/dev/directus-sveltekit-starter/svelte.config.js:22:33
 svelte:     at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
 svelte:     at async Promise.all (index 0)
 svelte:     at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
 svelte:     at async load_config (file:///C:/dev/directus-sveltekit-starter/node_modules/@sveltejs/kit/dist/cli.js:785:17)
 svelte:     at async file:///C:/dev/directus-sveltekit-starter/node_modules/@sveltejs/kit/dist/cli.js:887:19
 svelte: svelte-kit dev exited with code 1
--> Sending SIGTERM to other processes..
directus: pnpm run directus start exited with code 1

**Can you take a look please? :-)**

**Comment by maximimaxima** [comment]
Could you maybe make a version of this without WindiCSS? I think WindiCSS is obsolete anyway because Tailwind has JIT by default now.

**Comment by alteredorange** [comment]
@maximimaxima Hi Max. I haven't touched this repo in almost a year. Ran through the readme steps and everything still seems to work just fine, didn't get a windicss error (but I'm using pnpm instead of npm). I prefer windi for multiple reasons over Tailwind, but you're free to just remove the windi dependency and add Tailwind. There's quite a few guides out there if you google "add tailwind to sveltekit". Best of luck!
